INSERT INTO tb_category (name, created_at) VALUES ('Books', now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics', now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', now());
INSERT INTO tb_category (name, created_at) VALUES ('Clothing', now());
INSERT INTO tb_category (name, created_at) VALUES ('Home Goods', now());
INSERT INTO tb_category (name, created_at) VALUES ('Sports Equipment', now());
INSERT INTO tb_category (name, created_at) VALUES ('Musical Instruments', now());
INSERT INTO tb_category (name, created_at) VALUES ('Gaming Consoles', now());
INSERT INTO tb_category (name, created_at) VALUES ('Kitchen Appliances', now());
INSERT INTO tb_category (name, created_at) VALUES ('Outdoor Gear', now());
INSERT INTO tb_category (name, created_at) VALUES ('Beauty Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Pet Supplies', now());
INSERT INTO tb_category (name, created_at) VALUES ('Baby Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Office Supplies', now());
INSERT INTO tb_category (name, created_at) VALUES ('Automotive Parts', now());
INSERT INTO tb_category (name, created_at) VALUES ('Tools', now());
INSERT INTO tb_category (name, created_at) VALUES ('Artwork', now());
INSERT INTO tb_category (name, created_at) VALUES ('Collectibles', now());
INSERT INTO tb_category (name, created_at) VALUES ('Food and Beverages', now());
INSERT INTO tb_category (name, created_at) VALUES ('Health Supplements', now());
INSERT INTO tb_category (name, created_at) VALUES ('Travel Accessories', now());
                                                                                                                                                                                                                     INSERT INTO tb_category (name, created_at) VALUES ('Computers', now());
                                                                                                                                                                                                                     INSERT INTO tb_category (name, created_at) VALUES ('Books', now());
                                                                                                                                                                                                                                                                                            INSERT INTO tb_category (name, created_at) VALUES ('Electronics', now());
                                                                                                                                                                                                                                                                                            INSERT INTO tb_category (name, created_at) VALUES ('Computers', now());
                                                                                                                                                                                                                                                                                            INSERT INTO tb_category (name, created_at) VALUES ('Books', now());
                                                                                                                                                                                                                                                                                                                                                                   INSERT INTO tb_category (name, created_at) VALUES ('Electronics', now());
                                                                                                                                                                                                                                                                                                                                                                   INSERT INTO tb_category (name, created_at) VALUES ('Computers', now());